<a href="https://colab.research.google.com/github/opentrainingcamp/python/blob/main/Notebook/Data/DS02_Pandas_structureDonnees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Apprendre à connaître les structures de données de Pandas



Alors qu'un DataFrame fournit des fonctions qui peuvent sembler assez intuitives, les concepts sous-jacents sont un peu plus difficiles à comprendre. Pour cette raison, vous allez mettre de côté le vaste NBA DataFrame et créer des objets Pandas plus petits à partir de zéro.

## Comprendre les objets de série
La structure de données la plus élémentaire de Python est la liste, qui est également un bon point de départ pour apprendre à connaître les objets `pandas.Series`. Créez un nouvel objet Series basé sur une liste:

In [ ]:
l = ['a' , 1, 'toto']

In [ ]:
l[2]

'toto'

In [ ]:
d = { 'cle': '2', 3: 10, 'x':4}

In [ ]:
d['cle']

'2'

In [ ]:
d[3]

10

In [ ]:
d['newdata'] = {'x':1, 'y': 2}

In [ ]:
d

{3: 10, 'cle': '2', 'newdata': {'x': 1, 'y': 2}, 'x': 4}

In [ ]:
d['newdata']

{'x': 1, 'y': 2}

In [ ]:
import pandas as pd
revenues = pd.Series([5555, 7000, 1980])
revenues

0    5555
1    7000
2    1980
dtype: int64

Vous avez utilisé la liste [5555, 7000, 1980] pour créer un objet Série appelé revenus. Un objet Series encapsule deux composants:

* Une séquence de valeurs
* Une séquence d'identifiants, qui est l'index

Vous pouvez accéder à ces composants avec .values et .index, respectivement:

In [ ]:
print(revenues.index,revenues.values)

RangeIndex(start=0, stop=3, step=1) [5555 7000 1980]


In [ ]:
type(revenues.values)

numpy.ndarray

Alors que Pandas s'appuie sur NumPy, une différence significative réside dans leur indexation. Tout comme un tableau NumPy, une série Pandas possède également un index entier défini implicitement. Cet index implicite indique la position de l'élément dans la série.

Cependant, une série peut également avoir un type d'index arbitraire. Vous pouvez considérer cet index explicite comme des étiquettes pour une ligne spécifique:

In [ ]:
city_revenues = pd.Series(
    [4200, 8000, 6500],
    index=["Amsterdam", "Toronto", "Tokyo"]
)
# SQL : insert ("Amsterdam", "Toronto", "Tokyo") into city_r  values  (4200, 8000, 6500)
print(city_revenues.index,city_revenues.values)

Index(['Amsterdam', 'Toronto', 'Tokyo'], dtype='object') [4200 8000 6500]


En fait un mode de référencement par clé:valeur

In [ ]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

On peu utiliser les dictionnaire de Python pour initialiser une Serie

In [ ]:
city_employee_count = pd.Series({"Amsterdam": 5, "Tokyo": 8})
city_employee_count

Amsterdam    5
Tokyo        8
dtype: int64

Les clés du dictionnaire deviennent l'index et les valeurs du dictionnaire sont les valeurs Series.

Tout comme les dictionnaires, Series prend également en charge .keys () et le mot-clé in:

In [ ]:
print(city_employee_count.keys(),city_employee_count.values,city_employee_count.index)

Index(['Amsterdam', 'Tokyo'], dtype='object') [5 8] Index(['Amsterdam', 'Tokyo'], dtype='object')


# Comprendre les objets DataFrame
Bien qu'une série soit une structure de données assez puissante, elle a ses limites. Par exemple, vous ne pouvez stocker qu'un seul attribut par clé. Comme vous l’avez vu avec l’ensemble de données nba, qui comprend 23 colonnes, la bibliothèque Pandas Python a plus à offrir avec son DataFrame. Cette structure de données est une séquence d'objets Series qui partagent le même index.

Si vous avez suivi les exemples de séries, vous devriez déjà avoir deux objets de série avec des villes comme clés:

* city_revenues
* city_employee_count


Vous pouvez combiner ces objets dans un DataFrame en fournissant un dictionnaire dans le constructeur. Les clés du dictionnaire deviendront les noms de colonne et les valeurs doivent contenir les objets Series:

In [ ]:
print('revenues', city_revenues,'employé', city_employee_count, sep='\n----\n')

revenues
----
Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64
----
employé
----
Amsterdam    5
Tokyo        8
dtype: int64


In [ ]:
city_data = pd.DataFrame({
    "revenue": city_revenues,
    "employee_count": city_employee_count
})
city_data

revenue  employee_count
Amsterdam     4200             5.0
Tokyo         6500             8.0
Toronto       8000             NaN

Reamarque ce qui se passe pour Torento

In [ ]:
city_data.index

Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object')

In [ ]:
city_data.values

array([[4.2e+03, 5.0e+00],
       [6.5e+03, 8.0e+00],
       [8.0e+03,     nan]])

On peut également désigner les 2 dimensions d'un DataFrame comme des axes:

In [ ]:
print(city_data.axes)
print(city_data.axes[0],city_data.axes[1])

[Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object'), Index(['revenue', 'employee_count'], dtype='object')]
Index(['Amsterdam', 'Tokyo', 'Toronto'], dtype='object') Index(['revenue', 'employee_count'], dtype='object')


Un DataFrame est également une structure de données de type dictionnaire, il prend donc également en charge .keys () et le mot clé in. Cependant, pour un DataFrame, ceux-ci ne sont pas liés à l'index, mais aux colonnes:

In [ ]:
city_data.keys()

Index(['revenue', 'employee_count'], dtype='object')

### Revenons à notre exemple nba

In [ ]:
nba = pd.read_csv('https://github.com/fivethirtyeight/data/raw/master/nba-elo/nbaallelo.csv')
type(nba)

pandas.core.frame.DataFrame

In [ ]:
nba.index

RangeIndex(start=0, stop=126314, step=1)

In [ ]:
nba.axes

[RangeIndex(start=0, stop=126314, step=1),
 Index(['gameorder', 'game_id', 'lg_id', '_iscopy', 'year_id', 'date_game',
        'seasongame', 'is_playoffs', 'team_id', 'fran_id', 'pts', 'elo_i',
        'elo_n', 'win_equiv', 'opp_id', 'opp_fran', 'opp_pts', 'opp_elo_i',
        'opp_elo_n', 'game_location', 'game_result', 'forecast', 'notes'],
       dtype='object')]

In [ ]:
nba.keys()

Index(['gameorder', 'game_id', 'lg_id', '_iscopy', 'year_id', 'date_game',
       'seasongame', 'is_playoffs', 'team_id', 'fran_id', 'pts', 'elo_i',
       'elo_n', 'win_equiv', 'opp_id', 'opp_fran', 'opp_pts', 'opp_elo_i',
       'opp_elo_n', 'game_location', 'game_result', 'forecast', 'notes'],
      dtype='object')

Lorsque vous utilisez ces méthodes pour répondre à des questions sur votre ensemble de données, assurez-vous de garder à l'esprit si vous travaillez avec une série ou un DataFrame afin que votre interprétation soit précise.

## Accès aux éléments de la série
Dans la section ci-dessus, vous avez créé une série Pandas basée sur une liste Python et comparé les deux structures de données. Vous avez vu comment un objet Series est similaire à des listes et des dictionnaires de plusieurs manières. Une autre similitude est que vous pouvez également utiliser l'opérateur d'indexation ([]) pour Series.

Vous apprendrez également à utiliser deux méthodes d'accès spécifiques à Pandas:

* .loc
* .iloc

Vous verrez que ces méthodes d'accès aux données peuvent être beaucoup plus lisibles que l'opérateur d'indexation.

### Utilisation de l'opérateur d'indexation
Rappelez-vous qu'une série a deux indices:

1. Un index positionnel ou implicite, qui est toujours un RangeIndex
2. Une étiquette ou un index explicite, qui peut contenir tous les objets hachables

Ensuite, revisitez l'objet city_revenues:

In [ ]:
city_revenues

Amsterdam    4200
Toronto      8000
Tokyo        6500
dtype: int64

In [ ]:
city_revenues['Amsterdam']

4200

In [ ]:
city_revenues[0]

4200

In [ ]:
# Vous pouvez également utiliser des indices et des tranches négatifs, comme vous le feriez pour une liste:
city_revenues[-1]

6500

In [ ]:
city_revenues[1:]

Toronto    8000
Tokyo      6500
dtype: int64

In [ ]:
city_revenues["Toronto":]


Toronto    8000
Tokyo      6500
dtype: int64

### utilisation loc et iloc
L'opérateur d'indexation ([]) est pratique, mais il y a une mise en garde. Et si les étiquettes sont également des nombres? Supposons que vous deviez travailler avec un objet Series comme celui-ci:

In [ ]:
import pandas as pd
colors = pd.Series(
    ["red", "purple", "blue", "green", "yellow"],
    index=[1, 2, 3, 5, 8]
)
colors

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object

Que reviendront les coulor[1]? Pour un index positionnel, les coulor[1] sont "purple". Cependant, si vous passez par l'index des étiquettes, alors colors[1] fait référence au "rouge".

La bonne nouvelle est que vous n’avez pas à le découvrir! Au lieu de cela, pour éviter toute confusion, la bibliothèque Pandas Python fournit deux méthodes d'accès aux données:

1. .loc fait référence à l'index de l'étiquette (la clé).
2. .iloc fait référence à l'index de position.

Ces méthodes d'accès aux données sont beaucoup plus lisibles:

In [ ]:
print(colors)
print(f'loc[1]={colors.loc[1]}, iloc[1]={colors.iloc[1]}')

1       red
2    purple
3      blue
5     green
8    yellow
dtype: object
loc[1]=red, iloc[1]=purple


#### iloc position, loc clé
![loc iloc](https://github.com/lipug/datascience/raw/main/pandasIntro/loc_iloc.png)

.loc et .iloc prennent également en charge les fonctionnalités que vous attendez des opérateurs d'indexation, comme le découpage. Cependant, ces méthodes d'accès aux données présentent une différence importante. Alors que .iloc exclut l'élément de fermeture, .loc l'inclut. Jetez un œil à ce bloc de code:

In [ ]:
colors.loc[3:8]

3      blue
5     green
8    yellow
dtype: object

In [ ]:
#pas ceci
# colors.loc[-1]

# Mais cela
colors.iloc[-1]

'yellow'

# Accès aux éléments DataFrame (requêtes)

Puisqu'un DataFrame se compose d'objets Series, vous pouvez utiliser les mêmes outils pour accéder à ses éléments. La différence cruciale est la dimension supplémentaire du DataFrame. Vous utiliserez l'opérateur d'indexation pour les colonnes et les méthodes d'accès .loc et .iloc sur les lignes.

Utilisation de l'opérateur d'indexation
Si vous considérez un DataFrame comme un dictionnaire dont les valeurs sont Series, alors il est logique que vous puissiez accéder à ses colonnes avec l'opérateur d'indexation:

In [ ]:
city_revenues = pd.Series(
    [4200, 8000, 6500],
    index=["Amsterdam", "Toronto", "Tokyo"]
)

city_employee_count = pd.Series({"Amsterdam": 5, "Tokyo": 8})

city_data = pd.DataFrame({
    "revenue": city_revenues,
    "employee_count": city_employee_count
})

In [ ]:
city_data["revenue"]

Amsterdam    4200
Tokyo        6500
Toronto      8000
Name: revenue, dtype: int64

In [ ]:
type(city_data["revenue"])

pandas.core.series.Series

Ici, vous utilisez l'opérateur d'indexation pour sélectionner la colonne intitulée "revenus".

INTERESSANT: Si le nom de la colonne est une chaîne, vous pouvez également utiliser un accès de style attribut avec la notation par points:

In [ ]:
city_data.revenue

Amsterdam    4200
Tokyo        6500
Toronto      8000
Name: revenue, dtype: int64

In [ ]:
city_data.shape

(3, 2)

In [ ]:
city_data.describe()

revenue  employee_count
count     3.000000         2.00000
mean   6233.333333         6.50000
std    1913.983629         2.12132
min    4200.000000         5.00000
25%    5350.000000         5.75000
50%    6500.000000         6.50000
75%    7250.000000         7.25000
max    8000.000000         8.00000

In [ ]:
city_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Amsterdam to Toronto
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   revenue         3 non-null      int64  
 1   employee_count  2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 180.0+ bytes


# revenons a des exemples plus conséquents

In [ ]:
nba = pd.read_csv('https://github.com/fivethirtyeight/data/raw/master/nba-elo/nbaallelo.csv')
type(nba)

NameError: ignored

In [ ]:
nba.iloc[-1]

gameorder               63157
game_id          201506170CLE
lg_id                     NBA
_iscopy                     1
year_id                  2015
date_game           6/16/2015
seasongame                103
is_playoffs                 1
team_id                   GSW
fran_id              Warriors
pts                       105
elo_i               1813.6349
elo_n               1822.2881
win_equiv           68.519516
opp_id                    CLE
opp_fran            Cavaliers
opp_pts                    97
opp_elo_i           1700.7391
opp_elo_n           1692.0859
game_location               A
game_result                 W
forecast              0.51855
notes                     NaN
Name: 126313, dtype: object

Pour un DataFrame, les méthodes d'accès aux données .loc et .iloc acceptent également un deuxième paramètre. Alors que le premier paramètre sélectionne les lignes en fonction des indices, le second paramètre sélectionne les colonnes. Vous pouvez utiliser ces paramètres ensemble pour sélectionner un sous-ensemble de lignes et de colonnes dans votre DataFrame:

In [ ]:
nba.loc[5555:5559, ["fran_id", "opp_fran", "pts", "opp_pts"]]

fran_id  opp_fran  pts  opp_pts
5555  Pistons  Warriors   83       56
5556  Celtics    Knicks   95       74
5557   Knicks   Celtics   74       95
5558    Kings    Sixers   81       86
5559   Sixers     Kings   86       81

On a Sélectionné toutes les parties entre les étiquettes 5555 et 5559. Et étions interessé [ar les noms des équipes et aux scores.